### ISSUE TITLE
This app doesn't exists in OpenStore

### ISSUE THREAD

**Issue by advocatux** [turanmahmudov/Translate#1]
I can't find this app in the OpenStore.

Besides the link https://open.uappexplorer.com/app/translate.turan-mahmudov-l goes to a page which says: 

> The app you are looking for has been removed or does not exist

**Comment by turanmahmudov** [comment]
@advocatux I haven't finished the development of the application. I will be in the Store soon.

**Comment by turanmahmudov** [comment]
It's in the store btw.
